#!/usr/bin/env bash
# Install nginx web server
apt-get update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/e404.html
sed -i '/listen 80 default_server/a error_page 404 /e404.html;\nlocation =  /e404.html {\n\troot /var/www/html/;\n\tinternal;\n}' /etc/nginx/sites-available/default
service nginx restart
