#!/usr/bin/env bash
#install HAproxy (load balancer)
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get update -y
apt-get -y install haproxy=2.0.\*
sed -i '/errorfile 504/a frontend http_front\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend http_back\n\nbackend http_back\n\tbalance roundrobin\n\tserver 3341-web-01 35.243.245.64 check\n\tserver 3341-web-02 18.234.66.163 check' /etc/haproxy/haproxy.cfg
service haproxy restart
