#!/usr/bin/env bash
#install HAProxy (load balancer)

CONFIG="
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back
backend http_back
    balance roundrobin
    server web-01 35.243.245.64 check
    server web-02 18.234.66.163 check 
"
sudo add-apt-repository -y ppa:vbernat/haproxy-1.7
apt-get -y update
apt-get -y install haproxy
echo "$CONFIG" >> /etc/haproxy/haproxy.cfg
service haproxy restart
