#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
while [ 0 -lt 10 ]
do
	if [ $n == 3 ]
	then
		echo "bad luck"
	elif [ $n == 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
    (( n++ ))
done
