#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
n=1
while [ $n -le 20 ]
do
	case $n in
	5)
		echo "bad luck from China"
		;;
	10)
		echo "bad luck from Japan"
		;;
	18)
		echo "bad luck from Italy"
		;;
	esac
	echo $n
    (( n++ ))
done
