#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
status_file=./school
if [ -e "$status_file" ]
then
	echo "school file exists"
	if [ -s "$status_file" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$status_file" ]
    then
        echo "holbertonschool is a regular file"
    fi
else
	echo "school file does not exist"
fi
