#!/usr/bin/env bash
# Script to run the whoami command under the user passed as an argument.
pkill -f apache2
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
